[build]
  publish = "site"
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-chromium"
    [plugins-inputs]
        packageManager =  "yarn"
        setChromePathInEnv = false
        failBuildOnError =  true